//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
/**
 * User model
 */
export type User = $ModelResult<$Schema, "User">;
/**
 * Post model
 */
export type Post = $ModelResult<$Schema, "Post">;
/**
 * OAuth2 registered clients
 */
export type OAuthClient = $ModelResult<$Schema, "OAuthClient">;
/**
 * OAuth2 authorization codes
 */
export type AuthorizationCode = $ModelResult<$Schema, "AuthorizationCode">;
/**
 * OAuth2 access tokens
 */
export type AccessToken = $ModelResult<$Schema, "AccessToken">;
/**
 * OAuth2 refresh tokens
 */
export type RefreshToken = $ModelResult<$Schema, "RefreshToken">;
